 # Hypothesis Testing for Income Census data

In [2]:
# import required libraries

import pandas as pd
import numpy as np

import statsmodels.formula.api as smf
from scipy.stats import chi2_contingency

In [3]:
# dataset path
file_path = "../income_dataset/"

In [4]:
# declare the column names test and train files dont have headers.
columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

# load the data
df_train = pd.read_csv(file_path + "adult.data", header=None, names=columns, sep=",",skipinitialspace=True)
df_test = pd.read_csv(file_path + "adult.test", header=None, names=columns, sep=",", skipinitialspace=True, skiprows=1)

# concatenate both datasets
df = pd.concat([df_train,df_test],axis = 0 , ignore_index=True)

In [5]:
print(df.shape)
df.head()

(48842, 15)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [7]:
print(df['income'].value_counts())

income
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [8]:
# standardize the income caegories

df['income'] = (df['income'].str.strip().str.replace('.','',regex=False))

In [9]:
print(df['income'].nunique())
print(df['income'].value_counts())

2
income
<=50K    37155
>50K     11687
Name: count, dtype: int64

# hypothesis question : Age vs Income

In [10]:
# hypothesis question
# Does age affect the probability of Income
# H0 - Age does not affect the probability of earning > 50K
# H1 - Age significantly affects the probability of earngin > 50K



# 1 = >50K, 0 = <=50K
df['income_binary'] = (df['income'] == '>50K').astype(int)


model = smf.logit (formula = "income_binary ~ age",data=df)
result = model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.524280
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:          income_binary   No. Observations:                48842
Model:                          Logit   Df Residuals:                    48840
Method:                           MLE   Df Model:                            1
Date:                Mon, 09 Feb 2026   Pseudo R-squ.:                 0.04720
Time:                        11:59:20   Log-Likelihood:                -25607.
converged:                       True   LL-Null:                       -26875.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.7228      0.035    -78.308      0.000      -2.791      -2.655
age            0.0387      0.001     49.321      0.000       0.037       0.040
==============================================================================

#### - Convert logistic regression coefficient from log-odds to odds ratio
#### - In logistic regression, coef represents change in log-odds of the outcome per unit increase in predictor
#### - np.exp(coef) gives the odds ratio, which is easier to interpret:
####   - OR > 1 means higher odds of outcome as predictor increases
####   - OR < 1 means lower odds
#### - Example: coef = 0.0387 → odds ratio ≈ 1.0395 --> each 1-year increase in age raises odds of earning >50K by ~3.95%

In [11]:
np.exp(0.0387)

1.039458599290056

#### Results : 
Age coefficient = 0.0387 - Each year of age increases the probability of earning > 50K by about 3.95%
Pseudo R² = 0.0472 - Age alone explains ~4.7% of the variation in income
p-value for age = 0.000  < 0.05 --> reject H0 null hypothesis. age is statistically significant
Conclusion : age is significant preditor of income, older individuals having higher probability of earning > 50K

---
---

# Hypothesis 2: Race vs Income
#### H0: Race has no effect on income (person’s race does not change the likelihood of earning >50K or ≤50K).
#### H1 : Race has an effect on income (person’s race changes the likelihood of earning >50K or ≤50K).

In [12]:

# Create a contingency table
contingency = pd.crosstab(df['race'], df['income'])

# Perform Chi-square test
chi2, p, dof, expected = chi2_contingency(contingency)

# Print results
print("Chi-square statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

# Interpretation
if p < 0.05:
    print("Reject H0: Race and income are not independent (significant relationship).")
else:
    print("Fail to reject H0: No significant relationship between race and income.")

Chi-square statistic: 487.026286837627
p-value: 4.284377710223499e-104
Degrees of freedom: 4
Expected frequencies:
 [[  357.53757012   112.46242988]
 [ 1155.53099791   363.46900209]
 [ 3563.96492773  1121.03507227]
 [  308.85160313    97.14839687]
 [31769.11490111  9992.88509889]]
Reject H0: Race and income are not independent (significant relationship).

#### -Race vs Income Analysis
#### -The Chi-square test shows a very strong association between race and income (Chi-square = 487.03, df = 4, p < 0.001).
#### -The expected frequencies (the counts we would expect if race had no effect on income) differ from the actual observed counts, which is why the test is highly significant.
#### -Conclusion: Race has a significant effect on income — the likelihood of earning >50K varies across different racial groups.

#### - Degrees of freedom tell us how many independent pieces of information are used to calculate the Chi-square statistic.
#### - dof=(number of rows−1)×(number of columns−1)
#### -      Rows = number of categories in one variable (e.g., races)
#### -      Columns = number of categories in the other variable (e.g., income groups)

---

# Hypothesis : Marital status vs Income
#### - H0 : Income level is independent of marital status
#### - H1 : Income level is dependednt of marital status

In [13]:
# Create contingency table
income_cont = pd.crosstab(df['marital_status'], df['income'])

#chi-square test
chi2, p, dof, expected = chi2_contingency(income_cont)

print("Chi-square statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)

Chi-square statistic: 9816.015037266438
p-value: 0.0
Degrees of freedom: 6

#### - Since the p-value is less than 0.05, we reject the null hypothesis. 
#### - There is a statistically significant association between marital status and income level.
#### - Income (>50K vs ≤50K) differs significantly across marital-status categories.

# Hypothesis : Country and education levels association with Income

In [14]:
# First, define the groups
low_edu = [
    'Preschool','1st-4th','5th-6th','7th-8th',
    '9th','10th','11th','12th','HS-grad'
]

high_edu = [
    'Bachelors','Prof-school','Assoc-acdm',
    'Assoc-voc','Masters','Doctorate'
]

# Create a new column in the dataframe
df['education_group'] = df['education'].apply(
    lambda x: 'low_edu' if x in low_edu else ('high_edu' if x in high_edu else 'Other')
)
print(df['education_group'].value_counts())

education_group
low_edu     22192
high_edu    15772
Other       10878
Name: count, dtype: int64

In [15]:


model = smf.logit(
    "income_binary ~ C(education_group) + C(native_country)",
    data=df
).fit()

print(model.summary())
'''odds_ratios = pd.DataFrame({
    "OR": np.exp(model.params),
    "Lower 95% CI": np.exp(model.conf_int()[0]),
    "Upper 95% CI": np.exp(model.conf_int()[1]),
    "p-value": model.pvalues
})
print(odds_ratios)'''

Optimization terminated successfully.
         Current function value: 0.500619
         Iterations 33
                           Logit Regression Results
==============================================================================
Dep. Variable:          income_binary   No. Observations:                48842
Model:                          Logit   Df Residuals:                    48798
Method:                           MLE   Df Model:                           43
Date:                Mon, 09 Feb 2026   Pseudo R-squ.:                 0.09020
Time:                        11:59:32   Log-Likelihood:                -24451.
converged:                       True   LL-Null:                       -26875.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
Intercept                                          -1.5680      0.085    -18.370      0.000      -1.735      -1.401
C(education_group)[T.high_edu]                      1.1580      0.029     39.365      0.000       1.100       1.216
C(education_group)[T.low_edu]                      -0.4255      0.032    -13.407      0.000      -0.488      -0.363
C(native_country)[T.Cambodia]                       0.6697      0.433      1.545      0.122      -0.180       1.519
C(native_country)[T.Canada]                         0.5195      0.185      2.815      0.005       0.158       0.881
C(native_country)[T.China]                          0.0724      0.224      0.323      0.746      -0.367       0.511
C(native_country)[T.Columbia]                      -1.6895      0.526     -3.211      0.001      -2.721      -0.658
C(native_country)[T.Cuba]                           0.1551      0.224      0.693      0.488      -0.283       0.594
C(native_country)[T.Dominican-Republic]            -1.3690      0.472     -2.900      0.004      -2.294      -0.444
C(native_country)[T.Ecuador]                       -0.4869      0.460     -1.058      0.290      -1.389       0.415
C(native_country)[T.El-Salvador]                   -0.9474      0.329     -2.878      0.004      -1.593      -0.302
C(native_country)[T.England]                        0.5222      0.212      2.466      0.014       0.107       0.937
C(native_country)[T.France]                         0.5141      0.354      1.453      0.146      -0.179       1.208
C(native_country)[T.Germany]                        0.1044      0.182      0.574      0.566      -0.252       0.461
C(native_country)[T.Greece]                         0.8107      0.326      2.489      0.013       0.172       1.449
C(native_country)[T.Guatemala]                     -1.6092      0.598     -2.691      0.007      -2.781      -0.437
C(native_country)[T.Haiti]                         -0.4816      0.375     -1.285      0.199      -1.216       0.253
C(native_country)[T.Holand-Netherlands]           -30.2687   8.19e+06   -3.7e-06      1.000   -1.61e+07    1.61e+07
C(native_country)[T.Honduras]                      -0.6842      0.768     -0.891      0.373      -2.189       0.821
C(native_country)[T.Hong]                          -0.0213      0.442     -0.048      0.961      -0.887       0.844
C(native_country)[T.Hungary]                        0.2323      0.527      0.441      0.659      -0.801       1.266
C(native_country)[T.India]                          0.3474      0.190      1.828      0.068      -0.025       0.720
C(native_country)[T.Iran]                           0.2516      0.291      0.864      0.387      -0.319       0.822
C(native_country)[T.Ireland]                        0.4895      0.391      1.251      0.211      -0.277       1.256
C(native_country)[T.Italy]                          0.7122      0.236      3.015      0.003       0.249       1.175
C(native_country)[T.Jamaica]                       -0.4790      0.300     -1.598      0.110      -1.066       0.108
C(native_country)[T.Japan]                          0.3677      0.245      1.502      0.133      -0.112       0.847
C(native_country)[T.Laos]                          -1.1265      0.762     -1.479      0.139      -2.620       0.367
C(native_country)[T.Mexico]                        -1.2323      0.172     -7.144      0.000      -1.570      -0.894
C(native_country)[T.Nicaragua]                     -1.3160      0.611     -2.153      0.031      -2.514      -0.118
C(native_country)[T.Outlying-US(Guam-USVI-etc)]    -1.9460      1.036     -1.878      0.060      -3.977       0.085
C(native_country)[T.Peru]                          -1.0997      0.542     -2.030      0.042      -2.161      -0.038
C(native_country)[T.Philippines]                    0.0871      0.158      0.552      0.581      -0.222       0.396
C(native_country)[T.Poland]                        -0.2404      0.294     -0.818      0.413      -0.816       0.336
C(native_country)[T.Portugal]                       0.2603      0.338      0.770      0.441      -0.402       0.923
C(native_country)[T.Puerto-Rico]                   -0.5125      0.257     -1.998      0.046      -1.015      -0.010
C(native_country)[T.Scotland]                      -0.5896      0.651     -0.906      0.365      -1.865       0.685
C(native_country)[T.South]                         -0.4699      0.268     -1.754      0.079      -0.995       0.055
C(native_country)[T.Taiwan]                         0.1929      0.272      0.710      0.478      -0.340       0.725
C(native_country)[T.Thailand]                      -0.6374      0.513     -1.243      0.214      -1.642       0.368
C(native_country)[T.Trinadad&Tobago]               -1.0261      0.753     -1.362      0.173      -2.502       0.450
C(native_country)[T.United-States]                  0.1360      0.083      1.640      0.101      -0.027       0.298
C(native_country)[T.Vietnam]                       -1.1971      0.411     -2.913      0.004      -2.003      -0.392
C(native_country)[T.Yugoslavia]                     0.7678      0.473      1.625      0.104      -0.158       1.694
===================================================================================================================

'odds_ratios = pd.DataFrame({\n    "OR": np.exp(model.params),\n    "Lower 95% CI": np.exp(model.conf_int()[0]),\n    "Upper 95% CI": np.exp(model.conf_int()[1]),\n    "p-value": model.pvalues\n})\nprint(odds_ratios)'

#### Higher education significantly increases the likelihood of earning more than 50K, regardless of country.
#### Country also affects income probabilities, with some countries showing higher or lower odds.
#### Overall, education is the strongest predictor of income in this dataset